name: saanjologin
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.30.1
  firebase_auth: ^4.19.4
  firebase_storage: ^11.0.0
  cloud_firestore: ^4.17.2
  google_sign_in: any
  mapbox_gl: ^0.16.0
  latlong2: ^0.9.1
  geolocator: ^11.0.0
  flutter_map_location_marker: any
  http: ^1.2.1
  image: ^3.0.1
  image_picker: ^0.8.7+3
  flutter_colorpicker: any
  mapbox_search: any
  

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/jeep.png
    - assets/ejeep.png
    - assets/jeepejeep.png
    - assets/logo.png
    - assets/apple.png
    - assets/Google.png
    - assets/logo2.png
    - assets/pin.png